version: '3.4'

services:
  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Chat.Api/Dockerfile
    links:
      - clickhouse
      - mongo

  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    ports:
      - 9000:9000
      - 8123:8123

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456